version: "3.8"
services:
  blenderpy-manylinux-wheel-builder:
    build:
      context: .
      dockerfile: ./.containers/Dockerfile
      target: blenderpy-manylinux-wheel-builder
    command: bash -c "/blenderpy/.vscode/tasks/unix/build.sh /Blender/blender && /blenderpy/.vscode/tasks/unix/build_manylinux_wheels.sh"
    container_name: blenderpy-manylinux-wheel-builder
    volumes: 
      - ./build:/build
      - ./Blender:/Blender:delegated
      - ./dist:/blenderpy/dist:delegated
  blenderpy-windows-wheel-builder:
    build:
      context: .
      dockerfile: ./.containers/Dockerfile
      target: blenderpy-windows-wheel-builder
    command: bash -c "/blenderpy/.vscode/tasks/unix/build.sh /Blender/blender && /blenderpy/.vscode/tasks/unix/build_manylinux_wheels.sh"
    container_name: blenderpy-windows-wheel-builder
    volumes: 
      - ./build:/build
      - ./Blender:/Blender:delegated
      - ./dist:/blenderpy/dist:delegated